// SillyTavern bridge — the retrofit that makes a QMM module live in the ST workbench:
//   toCharacterCard()  the module's protagonist as a Chara Card V2 (importable character)
//   toWorldInfo()      lore.json (+ optionally the beat templates) as an ST World Info book
// Round-trip: World Info edited in ST exports back through the existing lorebook importer
// (server/lorebook-import.mjs). Template entries are ONE-WAY rehearsal context — they carry the
// TEMPLATE_MARK prefix so the studio's import endpoint filters them out instead of re-importing
// them as lore.
//
// Field mapping mirrors convertLorebook exactly (key/keysecondary/comment/content/constant/
// caseSensitive/order/probability+useProbability/delay/cooldown/sticky/group/scanDepth/disable).

export const TEMPLATE_MARK = '[qmm-template]';

const bubbleJoin = (arr) => (arr || []).join('\n\n');

/**
 * @param {object} mod   engine-built module (buildModule output: manifest, pack, meta, intents…)
 * @returns {object} Chara Card V2 JSON (import via ST: Characters -> Import -> .json)
 */
export function toCharacterCard(mod) {
  const meta = mod.meta;
  const manifest = mod.manifest;
  const name = manifest.character?.name || 'Yuki';
  const firstFamily = mod.pack.families[0];
  const context = (firstFamily?.available_context || []).join('\n');

  // mes_example in ST's expected shape: <START> blocks of {{user}}/{{char}} lines. The module's
  // voice_example is character-side bubbles; present them as {{char}} turns.
  const mesExample = meta.voice_example
    ? '<START>\n' + meta.voice_example.split('\n').filter(l => l.trim()).map(l => `{{char}}: ${l.trim()}`).join('\n')
    : '';

  return {
    spec: 'chara_card_v2',
    spec_version: '2.0',
    data: {
      name,
      description: `${name} — the protagonist of "${meta.title}", a QMM interactive mystery told entirely as a text-message thread. The player is ${name}'s friend, texting in real time.\n\nWhat ${name} knows at the start:\n${context}`,
      personality: `Immediate, scared, intimate. Texts in short lowercase bubbles like a real person under pressure — one thought per message, sensory and concrete, never narrating, never summarizing the plot.`,
      scenario: `${meta.title}. The story advances in beats; between beats ${name} just texts — reacting, wondering, asking what to do.`,
      first_mes: bubbleJoin(meta.cold_open),
      mes_example: mesExample,
      creator_notes: [
        `Generated by the QMM Author Studio from module "${manifest.id}" v${manifest.version}.`,
        `Pair with the exported World Info book ("QMM — ${manifest.id}") for lore + beat-template rehearsal context.`,
        `Macro dialects differ: QMM uses {{random:a|b|c}} / {{pick:name:a|b|c}}; SillyTavern uses {{random:a,b,c}}. Cold-open macros (if any) may need adjusting for rehearsal.`,
        `Edits made in SillyTavern flow back via lorebook export -> studio Lore panel import. The card itself is one-way (regenerate after studio edits).`,
      ].join('\n'),
      system_prompt: '',
      post_history_instructions: '',
      alternate_greetings: [],
      tags: ['qmm', manifest.story_id || manifest.id, 'text-message', 'mystery'],
      creator: 'QMM Author Studio',
      character_version: manifest.version || '0.0.0',
      extensions: { qmm: { module_id: manifest.id, generated_from_version: manifest.version } },
    },
  };
}

/** One lore entry -> ST World Info entry (inverse of convertLorebook's mapping). */
function loreEntryToST(e, uid) {
  return {
    uid,
    key: (e.keys || []).map(String),
    keysecondary: [],
    comment: e.comment ? `${e.comment} [${e.id}]` : e.id,
    content: String(e.content || ''),
    constant: !!e.constant,
    selective: true,
    order: Number(e.order) || 100,
    position: 0,
    disable: e.enabled === false,
    addMemo: true,
    excludeRecursion: false,
    probability: e.probability === undefined ? 100 : Number(e.probability),
    useProbability: e.probability !== undefined && Number(e.probability) < 100,
    depth: 4,
    group: e.group || '',
    scanDepth: Number(e.scan_depth) > 0 ? Number(e.scan_depth) : null,
    caseSensitive: !!e.case_sensitive || null,
    delay: Number(e.delay) || 0,
    cooldown: Number(e.cooldown) || 0,
    sticky: Number(e.sticky) || 0,
  };
}

/**
 * @param {object} mod          engine-built module (pack has lore/rails merged)
 * @param {object} [options]
 * @param {boolean} [options.includeTemplates] add the beat templates as keyed rehearsal entries
 * @returns {object} ST World Info file JSON ({entries:{...}}), name-suggested "QMM — <id>"
 */
export function toWorldInfo(mod, { includeTemplates = false } = {}) {
  const entries = {};
  let uid = 0;
  for (const e of mod.pack.lore?.entries || []) {
    entries[uid] = loreEntryToST(e, uid);
    uid++;
  }
  if (includeTemplates) {
    for (const family of mod.pack.families) {
      for (const tpl of Object.values(family.templates || {})) {
        entries[uid] = {
          uid,
          key: [family.from, tpl.id],
          keysecondary: [],
          comment: `${TEMPLATE_MARK} ${tpl.id} — ${family.from} -> ${family.to} (${tpl.intent})`,
          content: `[beat template ${tpl.id}: ${family.from} -> ${family.to}, intent ${tpl.intent}]\n\n${tpl.template}\n\n[fill guidance]\n${(tpl.fill_guidance || []).map(g => `- ${g}`).join('\n')}`,
          constant: false,
          selective: true,
          order: 10,
          position: 0,
          disable: false,
          addMemo: true,
          excludeRecursion: true,
          probability: 100,
          useProbability: false,
          depth: 4,
          group: '',
          scanDepth: null,
          caseSensitive: null,
          delay: 0,
          cooldown: 0,
          sticky: 0,
        };
        uid++;
      }
    }
  }
  return { entries };
}

/** Strip one-way template entries from an ST book before re-import (pollution guard). */
export function stripTemplateEntries(book) {
  if (!book?.entries) return { book, stripped: 0 };
  const kept = {};
  let stripped = 0;
  for (const [k, e] of Object.entries(book.entries)) {
    if (String(e?.comment || '').includes(TEMPLATE_MARK)) { stripped++; continue; }
    kept[k] = e;
  }
  return { book: { ...book, entries: kept }, stripped };
}
